### ISSUE TITLE
asyncio implementation

### ISSUE THREAD

**Issue by sander76** [alysivji/finite-state-machine#27]
Looking at the source code de decorator don't seem to work when wrapping an async function

**Comment by alysivji** [comment]
Love this idea! After some Googling, it doesn't seem like it would be too much work to implement.

Would love help getting this feature implemented! If nobody picks it up, I'll try to get to it in the next few weeks.

### Helpful Resources

- [https://aikikode.me/blog/python-decorators-manual/#asynchronous-decorators](https://gist.github.com/Integralist/fb1b5dbb6271632298f44d62a2221905) hard to implement
- [https://aikikode.me/blog/python-decorators-manual/#asynchronous-decorators](https://aikikode.me/blog/python-decorators-manual/#asynchronous-decorators)
- [StackOverflow](https://stackoverflow.com/questions/42043226/using-a-coroutine-as-decorator)
- [Python & Async Simplified](https://www.aeracode.org/2018/02/19/python-async-simplified/)

**Comment by liuuuk311** [comment]
Hey @alysivji love your project! I actually edited to work my asyncio project. It's really easy to implement, I'd like to help you out! Let me know how to procede!

**Comment by alysivji** [comment]
I spent a couple of hours getting this working I started using asyncio at work.

#### Use Cases

- [ ] async methods inside of state machine
- [ ] async conditional functions

Will implement this functionality as 2 separate PRs with maybe a cleanup PR.

**Comment by alysivji** [comment]
Closed via #33
